import subprocess
import time
import pyautogui


class Researcher:
    """AI-powered research automation tool."""

    @staticmethod
    def write_research_report(topic: str, content: str):
        try:
            subprocess.Popen("notepad.exe")
            time.sleep(1.2)
            header = f"{'=' * 60}\n"
            header += f"NUETRON RESEARCH SHEET: {topic.upper()}\n"
            header += f"{'=' * 60}\n"
            header += "Generated by: Nuetron AI (Local Ollama Engine)\n"
            header += f"{'=' * 60}\n\n"
            full_text = header + content
            pyautogui.write(full_text, interval=0.01)
        except Exception as e:
            print(f"Research report error: {e}")

    @staticmethod
    def format_research_content(topic: str, insights: str, analysis: str, conclusions: str) -> str:
        formatted = f"""
TOPIC: {topic}

KEY INSIGHTS:
{insights}

DETAILED ANALYSIS:
{analysis}

CONCLUSIONS & RECOMMENDATIONS:
{conclusions}

---
Report generated by NUETRON v16 Research Assistant
"""
        return formatted

    @staticmethod
    def save_research_to_file(filename: str, content: str):
        try:
            with open(filename, "w", encoding="utf-8") as f:
                f.write(content)
        except Exception as e:
            print(f"File save error: {e}")
